# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nikkorobk.com
title: Chamomile Tea Collection
email: nikkorobk@gmail.com
author: Nikita Korobkov
description: Chamomile tea bags collection with photos.
copyright: 'Copyright &copy; 2019 Nikita Korobkov.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


social:
  - title: telegram
    icon: telegram
    url: https://t.me/insolia
  - title: email
    icon: envelope
    url: mailto:nikkorobk@gmail.com
  - title: github
    icon: github
    url: https://github.com/nkorobkov/chamomile


#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: linkedin
#    url: 
